//normal action
export const GET_ALL_PROJECT_CATEGORIES = 'GET_ALL_PROJECT_CATEGORIES';
export const GET_ALL_PROJECT_LIST = 'GET_ALL_PROJECT_LIST';

// saga action
export const GET_ALL_PROJECT_CATEGORIES_SAGA = 'GET_ALL_PROJECT_CATEGORIES_SAGA';
export const CREATE_PROJECT_SAGA = 'CREATE_PROJECT_SAGA';
export const GET_ALL_PROJECT_LIST_SAGA = 'GET_ALL_PROJECT_LIST_SAGA';