//normal action
export const GET_ALL_PROJECT_CATEGORIES = 'GET_ALL_PROJECT_CATEGORIES';
export const GET_ALL_PROJECT_LIST = 'GET_ALL_PROJECT_LIST';
export const SET_SUBMIT_CREATE_TASK = 'SET_SUBMIT_CREATE_TASK';
export const CHANGE_DETAIL_TASK_MODAL= 'CHANGE_DETAIL_TASK_MODAL';
// saga action
export const GET_ALL_PROJECT_CATEGORIES_SAGA = 'GET_ALL_PROJECT_CATEGORIES_SAGA';
export const CREATE_PROJECT_SAGA = 'CREATE_PROJECT_SAGA';
export const GET_ALL_PROJECT_LIST_SAGA = 'GET_ALL_PROJECT_LIST_SAGA';
export const GET_TASK_TYPE_SAGA = 'GET_TASK_TYPE_SAGA';
export const GET_TASK_TYPE = 'GET_TASK_TYPE';
export const GET_PRIORITY_SAGA = 'GET_PRIORITY_SAGA';
export const GET_PRIORITY = 'GET_PRIORITY';
export const GET_ALL_USER_SAGA= 'GET_ALL_USER_SAGA';
export const GET_ALL_USER= 'GET_ALL_USER';
export const CREATE_TASK_SAGA= 'CREATE_TASK_SAGA';
export const GET_ALL_STATUS_ID_SAGA = 'GET_ALL_STATUS_ID_SAGA';
export const GET_ALL_STATUS_ID = 'GET_ALL_STATUS_ID';
export const GET_MEMBERS_BY_PROJECT_ID_SAGA = 'GET_MEMBERS_BY_PROJECT_ID_SAGA';
export const GET_MEMBERS_BY_PROJECT_ID = 'GET_MEMBERS_BY_PROJECT_ID';
export const GET_DETAIL_TASK_SAGA= 'GET_DETAIL_TASK_SAGA';
export const GET_DETAIL_TASK = 'GET_DETAIL_TASK_';
