//normal action
export const GET_ALL_PROJECT_CATEGORIES = 'GET_ALL_PROJECT_CATEGORIES';
export const GET_ALL_PROJECT_LIST = 'GET_ALL_PROJECT_LIST';

// saga action
export const GET_ALL_PROJECT_CATEGORIES_SAGA = 'GET_ALL_PROJECT_CATEGORIES_SAGA';
export const CREATE_PROJECT_SAGA = 'CREATE_PROJECT_SAGA';
export const GET_ALL_PROJECT_LIST_SAGA = 'GET_ALL_PROJECT_LIST_SAGA';
export const GET_TASK_TYPE_SAGA = 'GET_TASK_TYPE_SAGA';
export const GET_TASK_TYPE = 'GET_TASK_TYPE';
export const GET_PRIORITY_SAGA = 'GET_PRIORITY_SAGA';
export const GET_PRIORITY = 'GET_PRIORITY';
export const GET_ALL_USER_SAGA= 'GET_ALL_USER_SAGA';
export const GET_ALL_USER= 'GET_ALL_USER';
export const CREATE_TASK_SAGA= 'CREATE_TASK_SAGA';